## NUMPY
### Arrays

In [15]:
import numpy as np

# Rank 1 Array (1D)
a = np.array([1, 2, 3])  
print(type(a))     # <class 'numpy.ndarray'>
print(a.shape)     # (3,)
print(a[0], a[1], a[2])  # 1 2 3
a[0] = 5   
print(a)          # [5, 2, 3]

# Rank 2 Array (2D)
b = np.array([[1,2,3], [4,5,6]])  
print(b.shape)     # (2, 3)
print(b[0, 0], b[0, 1], b[1, 0])  # 1 2 4

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


In [16]:
# 1️ 2x2 Zero Matrix
a = np.zeros((2,2))    
print(a)  
# [[0. 0.]
#  [0. 0.]]

# 2️ 1x2 Ones Matrix
b = np.ones((1,2))    
print(b)  
# [[1. 1.]]

# 3️ 2x2 Constant Matrix (Filled with 7)
c = np.full((2,2), 7)   
print(c)  
# [[7. 7.]
#  [7. 7.]]

# 4️ 2x2 Identity Matrix
d = np.eye(2)          
print(d)  
# [[1. 0.]
#  [0. 1.]]

# 5️ 2x2 Random Matrix (Values will vary)
e = np.random.random((2,2))  
print(e)  
# Example output:
# [[0.52 0.71]
#  [0.93 0.12]]

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.09532002 0.69321415]
 [0.73715399 0.03360605]]


### Array indexing

In [17]:
# 3x4 Matrix 
a = np.array([[1,2,3,4], 
              [5,6,7,8], 
              [9,10,11,12]])

# a-subset (Slice): 1st 2 Row & 2 Column (Column index 1-2)
b = a[:2, 1:3]

print(a)  
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]

print(b)  
# [[2 3]
#  [6 7]]

print(a[0, 1])  # Prints "2"

# if b changes then a change (Because 'b' is a view of 'a')
b[0, 0] = 77  

print(a[0, 1])  # Prints "77" (main Array-change!)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]
2
77


In [18]:
a = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8], 
              [9,10,11,12]])

# Rank 1 View (a 1D Array)
row_r1 = a[1, :]  
print(row_r1, row_r1.shape)  
# Output: [5 6 7 8] (4,)  → 1D Array

# Rank 2 View (a 2D Array)
row_r2 = a[1:2, :]  
print(row_r2, row_r2.shape)  
# Output: [[5 6 7 8]] (1, 4) → 2D Array

# Column slicing - Rank 1 View
col_r1 = a[:, 1]  
print(col_r1, col_r1.shape)  
# Output: [ 2  6 10] (3,)  → 1D Array

# Column slicing - Rank 2 View
col_r2 = a[:, 1:2]  
print(col_r2, col_r2.shape)  
# Output: 
# [[ 2] 
#  [ 6] 
#  [10]]  (3, 1) → 2D Array

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [19]:
a = np.array([[1, 2], 
              [3, 4], 
              [5, 6]])

# using Multiple specific indices to calculate value (Integer Array Indexing)
print(a[[0, 1, 2], [0, 1, 0]])  
# Output: [1 4 5]

# same (Manually):
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  
# Output: [1 4 5]

# same index repeated using:
print(a[[0, 0], [1, 1]])  
# Output: [2 2]

# same above code:
print(np.array([a[0, 1], a[0, 1]]))  
# Output: [2 2]

[1 4 5]
[1 4 5]
[2 2]
[2 2]


In [20]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # prints "array([[ 1,  2,  3],
          #                [ 4,  5,  6],
          #                [ 7,  8,  9],
          #                [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10

print(a)  # prints "array([[11,  2,  3],
          #                [ 4,  5, 16],
          #                [17,  8,  9],
          #                [10, 21, 12]])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


### Boolean array indexing:


In [21]:
a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)   # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2.

print(bool_idx)      # Prints "[[False False]
                     #          [ True  True]
                     #          [ True  True]]"

# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])  # Prints "[3 4 5 6]"

# We can do all of the above in a single concise statement:
print(a[a > 2])     # Prints "[3 4 5 6]"

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


### Math

In [22]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x + y)         # Element-wise sum
print(np.add(x, y))  # Alternative method

print(x - y)         # Element-wise subtraction
print(np.subtract(x, y))

print(x * y)         # Element-wise multiplication
print(np.multiply(x, y))

print(x / y)         # Element-wise division
print(np.divide(x, y))

print(np.sqrt(x))    # Element-wise square root


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [23]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

print(v.dot(w))       # Inner product: 9*11 + 10*12 = 219
print(np.dot(v, w))   # Same as above

x = np.array([[1,2],[3,4]])
print(x.dot(v))       # Matrix-vector product
print(np.dot(x, v))   # Same result

y = np.array([[5,6],[7,8]])
print(x.dot(y))       # Matrix-matrix product
print(np.dot(x, y))   # Same result


219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [24]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))         # Total sum of all elements: 1+2+3+4 = 10
print(np.sum(x, axis=0)) # Sum of each column: [1+3, 2+4] = [4, 6]
print(np.sum(x, axis=1)) # Sum of each row: [1+2, 3+4] = [3, 7]


10
[4 6]
[3 7]


In [25]:
x = np.array([[1,2], [3,4]])
print(x)
print(x.T)  # Transpose: Rows become columns & vice versa
v = np.array([1,2,3])
print(v) 
print(v.T)  # Transpose of 1D array does nothing

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


### Broadcasting

In [26]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [30]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [28]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]
